# Generated by Django 2.2.9 on 2020-04-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbs',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
