# Generated by Django 2.2.11 on 2020-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0002_auto_20200401_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrcalendar',
            options={'verbose_name': '资源日历', 'verbose_name_plural': '资源日历'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '成员', 'verbose_name_plural': '成员'},
        ),
        migrations.AlterModelOptions(
            name='wbs',
            options={'ordering': ('tree_id', 'lft'), 'verbose_name': 'WBS', 'verbose_name_plural': 'WBS'},
        ),
        migrations.AddField(
            model_name='hrcalendar',
            name='tasks_memo',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='任务说明'),
        ),
        migrations.AlterUniqueTogether(
            name='hrcalendar',
            unique_together={('work_date', 'staff')},
        ),
    ]
