# Generated by Django 2.2.9 on 2020-04-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0005_staff_man_day_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ac_rmb',
            field=models.FloatField(default=0, help_text='单位：元', verbose_name='ac'),
        ),
        migrations.AddField(
            model_name='project',
            name='ev_rmb',
            field=models.FloatField(default=0, help_text='单位：元', verbose_name='ev'),
        ),
        migrations.AddField(
            model_name='project',
            name='man_day_price_avg',
            field=models.FloatField(default=0, help_text='单位：元', verbose_name='平均人天单价'),
        ),
        migrations.AddField(
            model_name='project',
            name='pv_rmb',
            field=models.FloatField(default=0, help_text='单位：元', verbose_name='pv'),
        ),
        migrations.AddField(
            model_name='wbs',
            name='ac_ymb',
            field=models.FloatField(default=0, help_text='实际成本，单位元'),
        ),
        migrations.AddField(
            model_name='wbs',
            name='ev_ymb',
            field=models.FloatField(default=0, help_text='完工价值，单位元'),
        ),
        migrations.AddField(
            model_name='wbs',
            name='pv_ymb',
            field=models.FloatField(default=0, help_text='计划价值，单位元'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='ev',
            field=models.FloatField(default=0, help_text='挣值，单位人天'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='pv',
            field=models.FloatField(default=0, help_text='计划价值，单元人天'),
        ),
    ]
