# Generated by Django 2.2.9 on 2020-04-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('djpmp', '0007_auto_20200402_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrcalendar',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, help_text='在此组中的用户可以浏览此项目信息', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='权限组'),
        ),
        migrations.AddField(
            model_name='staff',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Project', verbose_name='项目'),
        ),
    ]
