# Generated by Django 2.2.9 on 2020-04-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0008_auto_20200402_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcalendar',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Project', verbose_name='项目'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Project', verbose_name='项目'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hrcalendar',
            unique_together={('project', 'work_date', 'staff')},
        ),
    ]
