# Generated by Django 2.2.9 on 2020-04-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0011_auto_20200402_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('后端中级', '后端中级'), ('后端高级', '后端高级'), ('前端中级', '前端中级'), ('前端高级', '前端高级'), ('UI中级', 'UI中级'), ('UI高级', 'UI高级'), ('测试中级', '测试中级'), ('测试高级', '测试高级'), ('产品中级', '产品中级'), ('产品高级', '产品高级')], default='后端中级', max_length=64, verbose_name='角色'),
        ),
    ]
