# Generated by Django 2.2.9 on 2020-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0013_auto_20200407_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '项目成员', 'verbose_name_plural': '项目成员'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='man_day_price',
            field=models.FloatField(default=0, help_text='元/人天', verbose_name='人天单价'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=128, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='ac_ymb',
            field=models.FloatField(default=0, help_text='实际成本，单位元', verbose_name='实际成本'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='ev_ymb',
            field=models.FloatField(default=0, help_text='完工价值，单位元', verbose_name='完工价值'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='name',
            field=models.CharField(max_length=128, verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='pv_ymb',
            field=models.FloatField(default=0, help_text='计划价值，单位元', verbose_name='计划价值'),
        ),
    ]
