# Generated by Django 2.2.9 on 2020-04-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0014_auto_20200414_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcalendar',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djpmp.Staff', verbose_name='人员'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='work_date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
