# Generated by Django 2.2.9 on 2020-04-14 13:09

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

import djpmp.models


def create_first_company(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Company = apps.get_model("djpmp", "Company")
    Company.objects.create(name='默认公司')


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djpmp', '0015_auto_20200414_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.RunPython(create_first_company),
        migrations.RemoveField(
            model_name='staff',
            name='project',
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='staff',
            field=models.ForeignKey(limit_choices_to=djpmp.models.my_staff, on_delete=django.db.models.deletion.CASCADE,
                                    to='djpmp.Staff', verbose_name='人员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ac_rmb',
            field=models.FloatField(default=0, help_text='单位：元', verbose_name='AC'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ev_rmb',
            field=models.FloatField(default=0, help_text='单位：元', verbose_name='EV'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pv_rmb',
            field=models.FloatField(default=0, help_text='单位：元', verbose_name='PV'),
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户数据权限',
                'verbose_name_plural': '用户数据权限',
            },
        ),
        migrations.AddField(
            model_name='hrcalendar',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company',
                                    verbose_name='公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company',
                                    verbose_name='公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company',
                                    verbose_name='公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbs',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company',
                                    verbose_name='公司'),
            preserve_default=False,
        ),
    ]
