# Generated by Django 2.2.9 on 2020-04-14 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djpmp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djpmp', '0016_auto_20200414_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djpmp.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djpmp.Staff', verbose_name='人员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(limit_choices_to=djpmp.models.my_companies, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company', verbose_name='公司'),
        ),
    ]
