# Generated by Django 2.2.9 on 2020-04-16 02:49

from django.db import migrations, models
import django.db.models.deletion
import djpmp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0017_auto_20200414_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '人力资源', 'verbose_name_plural': '人力资源'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.AddField(
            model_name='hrcalendar',
            name='status',
            field=models.CharField(choices=[('待确认', '待确认'), ('已确认', '已确认')], default='待确认', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='company',
            field=models.ForeignKey(limit_choices_to=djpmp.models.my_companies, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='project',
            field=models.ForeignKey(limit_choices_to=djpmp.models.my_projects, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='staff',
            field=models.ForeignKey(limit_choices_to=djpmp.models.my_staff, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Staff', verbose_name='人员'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='tasks',
            field=models.ManyToManyField(blank=True, limit_choices_to=djpmp.models.my_tasks, to='djpmp.WBS'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(limit_choices_to=djpmp.models.my_companies, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='company',
            field=models.ForeignKey(limit_choices_to=djpmp.models.my_companies, on_delete=django.db.models.deletion.CASCADE, to='djpmp.Company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='ev',
            field=models.FloatField(default=0, help_text='挣值，单位：人天'),
        ),
        migrations.AlterField(
            model_name='wbs',
            name='pv',
            field=models.FloatField(default=0, help_text='计划价值，单位：人天'),
        ),
    ]
