# Generated by Django 2.2.9 on 2020-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0018_auto_20200416_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='权限码'),
        ),
    ]
