# Generated by Django 2.2.11 on 2020-04-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djpmp', '0019_project_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrcalendar',
            options={'verbose_name': '人力资源投入记录', 'verbose_name_plural': '人力资源投入记录'},
        ),
    ]
